name: Docker Publish

on:
  push:
    branches:
      - main  # Chỉ chạy workflow khi có sự thay đổi trên nhánh "main"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Sử dụng phiên bản Node.js 14

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t your-dockerhub-username/your-repo-name:latest .
      
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image
      run: docker push your-dockerhub-username/your-repo-name:latest
